application: running-champ
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  secure: always 

- url: /pictures
  static_dir: pictures
  secure: always

- url: /js
  static_dir: js
  secure: always

- url: /fonts
  static_dir: fonts
  secure: always

- url: /(.*\.html)
  mime_type: text/html
  static_files: \1
  upload: (.*\.html)
  application_readable: true
  secure: always

- url: /css
  static_dir: css
  secure: always

- url: /(login|createaccount)
  script: main.app
  secure: always

- url: .*
  script: main.app
  secure: always # -> https!

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
